### ISSUE TITLE
SNOMED CT in DICOM subtasks (4): Determine if the IDC has current or future use cases which may leverage portions of SNOMED CT in DICOM superset

### ISSUE THREAD

**Issue by DaveraGabriel** [cancerDHC/Terminology#6]
- [ ] 4a) Determine if the IDC has current or future use cases which may leverage portions of SNOMED CT in DICOM superset determined in step 3, including...
- [x] 4b) Determine which additional SNOMED CT content / concepts may be used by the ICD in the future 
- [x] 4c)Create a comprehensive inventory of present and future SNOMED CT in DICOM set of concepts utilized by the ICD
